In [2]:
# importer les librairies 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
# emplacement du fichier courant
import os
os.getcwd()

'C:\\Users\\nadia'

In [24]:
# importer le dataset
data = pd.read_excel('VoitureOccasion.xlsx')

In [38]:
data

Annee  Kilometrage  Nb chevaux    Marque    Prix
0    2005       250000           6      Audi   90000
1    2004       215000           7      Audi   85000
2    2010       145000           8       BMW  110000
3    2015        90000           6       BMW  130000
4    2017        65000           9  Mercedes  160000
5    2012       150000           7       BMW  120000
6    2010       160000           7      Audi   95000
7    2012       155000           7  Mercedes  120000
8    2015        85000           6       BMW  132000
9    2018        52000           6  Mercedes  175000
10   2014       130000           7      Audi  140000
11   2013       130000           7  Mercedes  140000
12   2013       170000           6       BMW  135000
13   2016       110000           6  Mercedes  155000
14   2019        55000           7      Audi  210000
15   2011       140000           7  Mercedes  111000
16   2009       158000           6       BMW   90000
17   2008       170000           6  Mercedes  105000
18   2016       105000           8      Audi  165000
19   2017        96000           8  Mercedes  190000
20   2010       210000           6  Mercedes  110000
21   2011       205000           7       BMW  100000
22   2011       215000           7  Mercedes  115000
23   2012       230000           6      Audi  115000
24   2012       235000           6  Mercedes  120000
25   2012       190000           8  Mercedes  110000
26   2017        76000           8       BMW  170000
27   2017        84000           6  Mercedes  195000
28   2017        84000           7      Audi  180000
29   2018        45000           7  Mercedes  220000
30   2014       180000           8      Audi  113500
31   2014       180000           8      Audi  113500
32   2015       145000           6      Audi  145500
33   2013       130000           7       BMW  124500
34   2013       130000           7       BMW  125000
35   2014       174000           8  Mercedes  135000
36   2014       168000           6       BMW  135000
37   2015       136000           7      Audi  145000
38   2017        90000           7  Mercedes  190000
39   2017        85000           6       BMW  176000
40   2017        65000           6  Mercedes  205000
41   2012       230000           6      Audi  120000
42   2012       235000           6  Mercedes  117000
43   2013       190000           8  Mercedes  125000
44   2017        76000           8       BMW  168000
45   2017        84000           6  Mercedes  188000
46   2017        84000           7      Audi  180000
47   2018        45000           7  Mercedes  215000
48   2014       180000           8      Audi  113500
49   2015       145000           6      Audi  145500

In [39]:
# on a mis dans X tous les colonnes sauf la derniere et on a mis dans Y la derniere colonne
X=data.iloc[:,:-1]
Y=data.iloc[:,-1]

In [40]:
X

Annee  Kilometrage  Nb chevaux    Marque
0    2005       250000           6      Audi
1    2004       215000           7      Audi
2    2010       145000           8       BMW
3    2015        90000           6       BMW
4    2017        65000           9  Mercedes
5    2012       150000           7       BMW
6    2010       160000           7      Audi
7    2012       155000           7  Mercedes
8    2015        85000           6       BMW
9    2018        52000           6  Mercedes
10   2014       130000           7      Audi
11   2013       130000           7  Mercedes
12   2013       170000           6       BMW
13   2016       110000           6  Mercedes
14   2019        55000           7      Audi
15   2011       140000           7  Mercedes
16   2009       158000           6       BMW
17   2008       170000           6  Mercedes
18   2016       105000           8      Audi
19   2017        96000           8  Mercedes
20   2010       210000           6  Mercedes
21   2011       205000           7       BMW
22   2011       215000           7  Mercedes
23   2012       230000           6      Audi
24   2012       235000           6  Mercedes
25   2012       190000           8  Mercedes
26   2017        76000           8       BMW
27   2017        84000           6  Mercedes
28   2017        84000           7      Audi
29   2018        45000           7  Mercedes
30   2014       180000           8      Audi
31   2014       180000           8      Audi
32   2015       145000           6      Audi
33   2013       130000           7       BMW
34   2013       130000           7       BMW
35   2014       174000           8  Mercedes
36   2014       168000           6       BMW
37   2015       136000           7      Audi
38   2017        90000           7  Mercedes
39   2017        85000           6       BMW
40   2017        65000           6  Mercedes
41   2012       230000           6      Audi
42   2012       235000           6  Mercedes
43   2013       190000           8  Mercedes
44   2017        76000           8       BMW
45   2017        84000           6  Mercedes
46   2017        84000           7      Audi
47   2018        45000           7  Mercedes
48   2014       180000           8      Audi
49   2015       145000           6      Audi

In [41]:
# gerer les varibales categorique

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Marque",OneHotEncoder(),[3])],remainder = "passthrough")
X = ct.fit_transform(X)

In [42]:
X

array([[1.000e+00, 0.000e+00, 0.000e+00, 2.005e+03, 2.500e+05, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.004e+03, 2.150e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.010e+03, 1.450e+05, 8.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 9.000e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.017e+03, 6.500e+04, 9.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.012e+03, 1.500e+05, 7.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.010e+03, 1.600e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.012e+03, 1.550e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.015e+03, 8.500e+04, 6.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.018e+03, 5.200e+04, 6.000e+00],
       [1.000e+00, 0.000e+00, 0.000e+00, 2.014e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00, 2.013e+03, 1.300e+05, 7.000e+00],
       [0.000e+00, 1.000e+00, 0.000e+00, 2.013e+03, 1.700e+05, 6.000e+00],
       [0.000e+00, 0.000e

In [53]:
# diviser le dataset 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [54]:
len(X)

50

In [55]:
len(X_train)

40

In [56]:
len(X_test)

10

In [59]:
# construire le modele
regressor = LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [67]:
# faire des predictions
Y_pred = regressor.predict(X_test)

In [68]:
Y_pred

array([156107.99207073, 194307.10494981, 129513.38506535, 125907.39238177,
       110976.27412283, 148300.21415251, 161177.62416953,  95542.01039855,
       169370.21333559,  56356.59703357])

In [63]:
Y_test

8     132000
14    210000
36    135000
48    113500
41    120000
37    145000
44    168000
21    100000
39    176000
1      85000
Name: Prix, dtype: int64

In [71]:
regressor.predict([[0,0,1,2021,9000,6]])

array([231066.67478309])